"""Init simplefeed test table

Revision ID: cff5ecc30e9b
Revises: 133b2e32b37c
Create Date: 2022-03-21 05:01:40.380348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff5ecc30e9b'
down_revision = '133b2e32b37c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
