version: "3.9"

services:
  database:
    image: postgres:latest
    env_file:
      - ".env"
    ports:
      - "${POSTGRES_PORT}"
    environment:
      PGDATA: "${POSTGRES_PGDATA}"
    networks:
      - "simplefeed-network"
    volumes:
      - "${POSTGRES_VOLUME}:${POSTGRES_PGDATA}"

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ".env"
    ports:
      - "${PGADMIN_PORT}"
    environment:
      SESSION_DB_PATH: "${PGADMIN_SESSION_DB_PATH}"
    depends_on:
      - "database"
    networks:
      - "simplefeed-network"
    volumes:
      - "${PGADMIN_VOLUMES}:${PGADMIN_SESSION_DB_PATH}"

  webapi:
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - "80:80"
    depends_on:
      - "database"
    networks:
      - "simplefeed-network"

networks:
  simplefeed-network:
    driver: "bridge"
